### ISSUE TITLE
Commented out debug statement

### ISSUE THREAD

**Issue by w2pc** [alash3al/Horus#19]
There is a commented out debug statement in Horus.php

**Comment by alash3al** [comment]
where is the debug the statement ?

**Comment by alash3al** [comment]
Where is the debug statement ??

**Comment by w2pc** [comment]
Line 1120 //var_dump($pattern);

**Comment by alash3al** [comment]
there is no problem with it 
`//var_dump($pattern);` it is just a comment and won't be a nuclear bomb in the code

**Comment by w2pc** [comment]
You are right, there is not problem with it. Just bad practice to commit
code with commented out debug statements

**Comment by alash3al** [comment]
> Just bad practice to commit .  
but i may say that this is not a problem nor a bad practice :)
every release may has a commented debug statement based on my vision :)
