### ISSUE TITLE
Don't know how to render vars in html

### ISSUE THREAD

**Issue by bykof** [alash3al/Horus#20]
Hey! I use your Framework and finally I found a framework which is really micro! Thanks for that.
So I am using your $result->render() function and don't really understand how to express the template language so the render function can overwrite the given variables with the values. Can you please help me?

**Comment by bykof** [comment]
Ok I got it. Sorry for the pointless opening of an issue ticket.
Greetings Michael

**Comment by alash3al** [comment]
sorry for the delay, really i'm sorry,
see this example:
```php
<?php
 // ...
 $res->render('tpl.html', ['var1' => "value1"])
```

> tpl.html
```html
<?= $var1 ?>
```
