### ISSUE TITLE
psr-0 autoload support

### ISSUE THREAD

**Issue by niceperson** [alash3al/Horus#21]
@alash3al 
its not really an issue but just want to ask if you could add the autoload support as stated.
thanks.

**Comment by alash3al** [comment]
Horus already has `autoload` support, and it is easy to setup your workspace
```php
  $app = new Horus;

  // register the packages directory
  // you can provide array of directories that contain your packages .
  $app->autoload("./packages");

  // initialize YourTestClass from the `./packages/YourTestClass.php` or `./packages/YourTestClass/YourTestClass.php`
  $this->ytc = new YourTestClass;
```

**Comment by niceperson** [comment]
thanks for replying. i knew about the autoload that horus provided.
what i was asking is the auto-generating autoload.

usually if installed with composer in the `bootstrap.php` or `index.php` etc we could just do

`require 'vendor/autoload.php'`

because the composer generating the classmap/namespaces/file/psr4 and stuffs there.
which i believe coming from the package.

currently i need to require 2 lines
1. is the vendor/autoload
2. is vendor/alas3al/horus/horus.php


but after few days i know how to work around this.
i could create an autoload by adding the lines below in my project's composer.json

`"autoload": {
        "psr-0": {
            "horus":"vendor/alash3al/horus"
        }
    }`

and it works!

so i'm going to close this.
sorry to bother you. btw thaks alot for horus 1 file library i like it alot.

**Comment by alash3al** [comment]
Ok, and you may also use this
https://packagist.org/packages/alash3al/horus  
`composer require alash3al/horus`
